export const BASE_URL = 'https://nonamejon-mediastorage.hf.space'
export const GAP = '7px'

export const data = [
  {
    id: 'omniscient-reader',
    name: "Omniscient Reader",
    poster: 'omniscient-reader.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACgzA/5sDeSTdWXVb0bqOslB29OEXmm4393-cab66iLMdr05k` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACgzQ/f8qdA5emyjuZgYNM35AMcBsaLZJv5Q48zlliHQr39RU` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACgzg/ESCrqz10rg4GtwzuXwxyjFqTGthauQB1cxVZqSxVAFA` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACgzw/Iuy3OcczUkm2MpdllyLriYMXdqxEo8eOr9kZe716KIg` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg0A/2d7IIqalYx0_T4_NgtQC7nkvMLbP9heeTXevaoX0WaQ` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg0Q/4tW0IfL6G4vHuHII_otrynyNC_8y2LPOtbbGMov_A9w` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg0g/V8jOrxrdavcFRbKLxXgIA_WeHVNKKWHTEcDTQHWmSNs` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg0w/VqWEjB5j63bswqxDanm_N2VQXtezvc811p6tLaCXzqw` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg1A/sxid7YM832FWi-M9SK8AUMcjflwHQTsAZLSf8OcjrTw` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg1Q/bjocbukTcKU0WYW6I2og0l5nCD5h5kz3hoexQBqkYSw` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg2A/pfxDWRHEL--A4v8i-uEsfXq7IT55CZ6V_pPmWRHxcS8` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg2Q/Xw0wLiTeFacn0hFoUtlac00os6HFaHT5SrYr6ZeL9j0` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg2g/qScjIrCV3S48c_In9mA6RAH9HNaaIapbum_BagzvHYc` },
      { id: 'chunk-14', name: 'Chunk 14', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg2w/Y22ru8imD2zIdcnqMF1GN8fKFOt0vWzvE8lDmEwz7fA` },
      { id: 'chunk-15', name: 'Chunk 15', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg3A/6dmpZFmMpfTRrG8_k98B9C29Df9vCxi-LYKdaiY6y08` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg3Q/WX28fHPuNgvhhtQ7qGuAes_uDpN1e9yQeRB_NovKJm8` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg3g/0IhrmOHcXZbXk4Kw9iu-p2ENj9wg24-x6hUxpujvM2I` },
      { id: 'chunk-18', name: 'Chunk 18', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg3w/iTAa2zj8qoMbUBzlFDDiWwGAp-oT6qXl8uN5A1e4IyY` },
      { id: 'chunk-19', name: 'Chunk 19', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg4Q/OZrXHiuEAk5cY44TbfQQKM81so1PP5Eb0C5MGZp_aUM` },
      { id: 'chunk-20', name: 'Chunk 20', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACg4g/dI6dMqvOecOv99OJs4W0NmrGP6ib90Ay2AEIFfnRzCk` },
    ]
  },
  {
    id: 'overgeared',
    name: 'Overgeared',
    poster: 'overgeared.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb4Q/e_AkGrjCkAIq5o3BAFBstGzY1xQUCtjxjdtGAl4NFNw` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb4w/JiXkRDozXU4WZDaTjdxUrHYOAG4Cb3N8ETUC_zARx0o` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb5w/wgZB6OVIctZYpOCXbfxTP62L0OR83fB9svvcBUVPK30` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb6A/XbGGJjlFLKb14yTul0dJufyYGkcFTZu-3-Q5fsKtPSA` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb6Q/374LGQLc2XYemFneEaQ6AvlaWin6Oud03WK3xtFa1ZI` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb6g/_USf-KCZXy16zInUyw_VUc1Vbdur0o8Wu_WXbbeHmck` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb7A/cJOQZ8D_qVILw6k_vqHZlf-41Hkw9FpkpbWOg-38__8` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJKoFCPAACb7Q/Uag74uCKkqPSjHkzPA5Qw_fplNDvrwVQgJpN6WlN34Q` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACdEg/wNSFpPNYd9FWlc54kiFIaAiWutHJZTAghMhbozykLMs` },
    ]
  },
  // {
  //   id: 'omniscient-reader-ru',
  //   name: "Всеведущий читатель",
  //   poster: 'omniscient-reader.jpg',
  //   parts: [
  //     { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKsVVUAACYvA/weHDb015DvxNhJhjtBYcGD8uXUFmH7eiBlkRwZFSLtg` },
  //     { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKsVVUAACYvQ/KgZXnKLM6EPvhYtnrF3X6Nz9J5MKNpySjCsc6VzW6Kc` },
  //   ]
  // },
  {
    id: 'solo-leveling',
    name: 'Solo Leveling',
    poster: 'solo-leveling.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfZA/nISQXQ8p6jTh3eBx76xbN6aMQPfxtftMwsHujO_5l4Q` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfZg/NyKPYORLSLXcY2Me7kWh4VEDSPMiyvZ_KL_izvrFXMA` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfaQ/gHtRLspdO9giXAL17hfEFDnD00P0EQrgUj70Hq3ZR2Y` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfaw/HNpa9jxRVupk4skBj8lSnmGb561vUREIUwt-Ea1AYt4` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfcg/a4Ybhsi7_L0LN55Eh2zIiTVzEUlIGYYiMp-eeRywIdk` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfdg/7vJ7yklmYdP2mVKyl6E2vZ9hvusX7gB9Duyxr8AZvYw` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfeA/eDsvYtsi16jnqvHVzzxikeMgnZSLVy3z0YasgTBtvso` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfeQ/t7wX7PSKQbCFCZzR1JjSdEx6HzAsc1kLJHcONdJ51Q4` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfeg/w7_EWyl5PsPnphcZUSBu0RbOJpon-MhTRTF_T05QZU0` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfew/kB1yGy5NzrMDYSEkQN2pa-PtZL6P4swgW6-j93U83sM` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACffA/CWg6EVsuncZgrWF_gwJC8FZWIx0AVGtpi0rh7RozhuA` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACffg/kyHiXzvLrznpjPWlkMYBzbPcTQg68AJaLvi2S5e54HM` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfhg/kx0FUXveU_W-jPewk6kSimBCmH0gehEcC8wyVtk2IQc` },
      { id: 'chunk-14', name: 'Chunk 14', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfjQ/fYJgGqpsQX6vKuNQU_hDLOSem0sTXqxq8zsMGarECFo` },
      { id: 'chunk-15', name: 'Chunk 15', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfjg/RCRBXVQC2L5GwGwJiFPOn6_yTYA_Tv_0hO5pCgt-bTw` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfjw/am2o9XLo1xvtSzHJvihKK2GDwdx1AsRV40zvW85kEUo` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfkQ/VmJoJZ8DmrRanSxboT9l4ITtjBJr4IP1UGVts3RbmvM` },
      { id: 'chunk-18', name: 'Chunk 18 (Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfkg/o-2Wos3dKMbr2Qm-QdMY2C6EpN71WHvWV_nNkCRK1aE` },
      { id: 'chunk-19', name: 'Chunk 19 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACfkw/TLawqbyyB9f41PP7SMF3muOXFQzEr_qYQKpLPaID1a8` },
      { id: 'chunk-20', name: 'Chunk 20 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJKmS9yAACflA/dnCeYcgohys-8r4ONPL1B5zgXmHz4i-0m8J28kJbleo` },
    ]
  },
  {
    id: 'solo-leveling-ragnarok',
    name: 'Solo Leveling: Ragnarok',
    poster: 'solo-leveling-ragnarok.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcDw/Jtm60Kq0wzoWpYAbvO-LcwQfnqvhLUUOQ3j_rNoQR8A` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcEA/K3ophIhDsT9bVTvZDr2dBcEgQSWhA83hzFfD8CcjBq4` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcEQ/QiW4tIgIY89repTSy723B4iFhpcaQpIzw2kwQ7nSVZg` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcFA/63RNILrXdFxs_UTS5jq-EjAvOllMhsFF6RrDewyfckQ` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcFw/IuNayaIaM_7xzc0MI_eFP7Qzvn-QEcder-2kVx6wWVk` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcGQ/eh-wfSLzW665UOLWWM5y0B1zRXww6-Fe1_A8A-8rHaI` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKoXlHAACcGg/ecdu_6kJSUN58mpdlyQxl1cDELnt3fVXdxt7zeA5gwQ` },
    ]
  },
  {
    id: 'the-boxer',
    name: 'The Boxer',
    poster: 'the-boxer.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW8w/XRrOdk-vUKvb0lzj4d11J3fdvvK7A5qAsFiVHRv7irg` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW9A/6TMMn8XycHZ2LiFIghQOVk9vnQ37Ac3sr9Z970dGRHg` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW9g/7lOUb6XXcjcRD8Wq4QrO6JaMW5DBYjDXMQZx34E8iJQ` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW9w/zWxu5ab59-3vIeKAXTigzNToC3Pmzs0v5R8VjFXRxHI` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW-w/gXjcPGB0byn9YcxI4zWwK1ModCYf87jEe3F74buPaLU` },
      { id: 'chunk-6', name: 'Chunk 6 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW_A/Br1C0fZhb3mQuF6XHAdCCUWnoSj7DC4hRezYLVe0vRU` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACW_Q/HZs3epOfWFbfBWuLWuhpNCSEtG6SvBwEwFYA2lz5xuU` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXAA/SOQlHy5NANoM_AO_fikxEoeIT5Ifm-wHG6qZRnJ0I-U` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXAQ/MiNbChLLxLje0o7JMUckk4vnTwZslp91rEzGblltK9M` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXBA/3RmV9RZETw57X8sbuyDvVtc5ZgOC6N8Rh-h75WzfRCk` },
      { id: 'chunk-11', name: 'Chunk 11 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXBQ/hCLApfeCLGo0Bo5pi4rNOseWnjKk1-tfFqBnDeSTKGA` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXBw/hxHqmq2w8CArNhIM48wgvMhVYgsFZVn4f0s5xtU1xOI` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXCQ/UANjLbTVsO0BBuUe7U_lqb5iEMqrR946RYfoet4jUZ8` },
      { id: 'chunk-14', name: 'Chunk 14 (Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXDg/BtMWkm1ECe854FusjofXRasH0sCp2aY_IhwrX--3Ry4` },
      { id: 'chunk-15', name: 'Chunk 15 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXDw/lX8mP1MmUwWYo2nGvRoqRNdQAI65d1J5G5BD1_qwH60` },
    ]
  },
  {
    id: 'lookism',
    name: 'Lookism',
    poster: 'lookism.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChBw/-M5aemIUKjJWYpPBSBtcjs7dDd5A_YRejA3awLhsRKc` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChCQ/D3y-10D12yn9jAJ-kdNHplNW2szs_66NNGJolX74QJc` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChCw/QPNKOJNQg8JRjb5aoi8QIOr9oBnW6FcOowyWgdxgJHg` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChEQ/n_cKqgoXWo5PBNAkJcEfR875M9uUA-OzSZ1EW9Ebj_M` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChFQ/H-6EI7QslUMKqA2q3NW-CQS5FId8X9a5Tv9ZP2YvEfs` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChGA/bqfZGuSXZcZYSceQBGhjHobyhXjWRa4c8V8wZTMdaYg` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChGg/11rrhliFWE2Cjm9Z8jJzJwUKcuic4Maf0HZsG0lf_wQ` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChGw/-YXnn4mp4DPxXQg6XrSvaBCVmAQzhI3C4r1z2NE_R-M` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChHg/isw-cZ533s_v-rdJ0noqyTX4C7RZlwq079D4j0uL4fw` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChHw/V-9KQvgkDdkOIrQDTqu_2No1NajFIZPAkXNh9m8fnDo` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChJQ/Lwn8qNFYVoLCO0lJiP-zZFTy3kgb-E8LxjBTOFPSyLM` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChJg/l7ou8wgcDD34B2ABD8IsPbMpfyF92FTf-WAOin6mt-E` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChKQ/wPGql4PtmSqskgVSOfZ51b6jxJ58OtcqCGsCm2dmljw` },
      { id: 'chunk-14', name: 'Chunk 14', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChKw/xK16dJOS1GUkH6G2PVM0qocydD45tAWESlVkCR0IKIk` },
      { id: 'chunk-15', name: 'Chunk 15', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChLA/AZqgctfaXiEW9-tIgKLZPob0lmSmos_Dp5Mixay2er8` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChLw/gDo3WMIDNaZ1judaMk5a8lqIg1uQqbOCFKr6_WUjDS0` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChNg/wM_WEEZIj1XEj3JrBY-geOcnGQizR9O6b905Qd0OOSQ` },
      { id: 'chunk-18', name: 'Chunk 18', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChNw/PIkVN-r34FN2bhtL4Ch9hK0UTbau_oTJi9_SuXSZkN8` },
      { id: 'chunk-19', name: 'Chunk 19', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChOg/S5LVAkUCrY_1dIx_fAzCACZiKYcYBOZyKZ0WMS44FNo` },
      { id: 'chunk-20', name: 'Chunk 20', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChPA/liSZpmQM1EqLOLNmi0nib69TiuaTc6NKhiWOndIz8u8` },
      { id: 'chunk-21', name: 'Chunk 21', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChfQ/SBA9oo9icq-u_VHVYUOOmukjQzZ81fcPFi_MlzjgJJ8` },
      { id: 'chunk-22', name: 'Chunk 22', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChgw/H2_K5gj5H0_XpKPtSCBzIDPR_3ovPNCPTcBfrFrP8YI` },
      { id: 'chunk-23', name: 'Chunk 23', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChiA/wqSdrjN-D6xFDYpBwVBLDwZNQrozG_yawThdZhfQXro` },
      { id: 'chunk-24', name: 'Chunk 24', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChiw/jllkrXuIKZVlb_tiyXkIN6719QbYzjJRKeOPAP6DFEM` },
      { id: 'chunk-25', name: 'Chunk 25', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChjg/P8EA-8CKsP_GddDC5plfIgWBX9y46SUFSQdxR_3aYUM` },
      { id: 'chunk-26', name: 'Chunk 26', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChkg/VhI6rzuRWUnaf-2Y3AsTsW4-YgAwrfr6PKBW1chiqMI` },
      { id: 'chunk-27', name: 'Chunk 27', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChlg/pp5AB032nAvwkoOrzUQfMyf-JMlic_pmsbiHdLHhujY` },
      { id: 'chunk-28', name: 'Chunk 28', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChmg/laT6MpgAZpLgCU1I6g5ASZmmUpgWr0hnyhvrRngnAZM` },
      { id: 'chunk-29', name: 'Chunk 29', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChng/T2mG6Lv4KN0IlJPixWSKDdLLlQrEVuzRjSvITVVpOto` },
      { id: 'chunk-30', name: 'Chunk 30', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChow/hoX24-0d5l1vmvL2zgIAbj4iH3M1YkJK8alYUB7RNN0` },
      { id: 'chunk-31', name: 'Chunk 31', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChww/R1F-9I1CPIxLAgy2CE5mdTOa56Q0pxIcltr4pEfZ6-4` },
      { id: 'chunk-32', name: 'Chunk 32', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChxw/IdK67UHjL_ChY0hzCI9Iods3kfec20ce_snCDNcVUXI` },
      { id: 'chunk-33', name: 'Chunk 33', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChyQ/rVhUQsuw3koznDBPXznQOjhgJnkqOtBpr4vGYyEfGCc` },
      { id: 'chunk-34', name: 'Chunk 34', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChyg/8_QKjGgx8LQyjnsAt2ZLbG7BfqnmoJTY3M0R7lfT_fk` },
      { id: 'chunk-35', name: 'Chunk 35', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChzA/QbCUbrPRmhcRdJ_uYELfXf7h4iyWEzRhaTvbDnSm1do` },
      { id: 'chunk-36', name: 'Chunk 36', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAAChzQ/7c_K06tfT2YCbpjHXv4_XdroKqHWFwZthxjbyzaNFNA` },
      { id: 'chunk-37', name: 'Chunk 37', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh0Q/Vxkdy9GI9AA1lSs8cPjVegbkSiNCyZSIccRdk4gce7o` },
      { id: 'chunk-38', name: 'Chunk 38', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh1Q/_MRtpn3TikfuR8gGTH7RUnANLor1yXE0a_BqDH1S_fc` },
      { id: 'chunk-39', name: 'Chunk 39', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh2A/4HU9QCld4YLnHDD8FULqtB_4VqD2jtJcRNyKQRSZiJk` },
    ]
  },
  {
    id: 'tower-of-god',
    name: 'Tower of God',
    poster: 'tower-of-god.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXLg/iJd-tXoVCnCKc8TH7EUviKQniRLyiLktXkOXxtV7SEk` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXMA/OKrjMMk1Jt5nR1Q2IpyM_1U1rQcMUKiHcHkKGXlNv-E` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXMg/-OvoKkexZNHiAumyXiBL0RJRrgPRSv_E5YOQFyuPAes` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXMw/1o9QqO61EWHvNVYSl7kEJc00k34YjDJfG7LmhL6t5tE` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXNA/FH0DssAyw0JA4vPAzEkeqbY4hARgjEWRJ8c60e7-sZI` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXNQ/gGBylJCqdtRqPDWNIbSmZP9iVS6iSxwsDBIz_Nr2nwE` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXNw/7icNKOhbogd6T0pqoi6XX5z-F2-4tTohUzsBJ0jc4zA` },
      { id: 'chunk-8', name: 'Chunk 8 (Season 1 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJKuHHJAACXOQ/pG6iwcpxNMwhj73EC2ixJz9TRL3vgtnhzLaBShZ6pQ8` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZgQ/Tym7pR2_U0p4iB37e7wyVWrtZP4dxfxwK_-9dX3l2Ro` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZgw/IANkzlzKifgiu9dWG15gtpWVXkbPkswvfboi-9S1zHA` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZhA/qPSP4DrSfB8-DD4-0anwAY5Wkgzq1go5tDt_o5T630A` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZhw/SmtMcfcPxHql82xiT8Nqmjlb1JbdAnKJuK4LoHCr7Rs` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZhw/SmtMcfcPxHql82xiT8Nqmjlb1JbdAnKJuK4LoHCr7Rs` },
      { id: 'chunk-14', name: 'Chunk 14', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZiQ/ZYjOyfBA3aXETLImC4GQ8NCA4NAuEyCVH1HQ1Do_TzY` },
      { id: 'chunk-15', name: 'Chunk 15', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZiw/MIadWJXckR1VRtdQZ-9qex5vb8eyPEwqOS_BsAb300s` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZjg/wlclf07ud1xMR16f9UAFiQTof-vSh8TvoyrNnOG-arw` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZjw/MO-RnbGbDz25ULwyj_uxYO2MQ9QHReKPwtbWwT_6qLk` },
      { id: 'chunk-18', name: 'Chunk 18', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZkA/QIcaeNF2XRfGUcD0hdctjSI3GBpEhLSJeucRJRssxps` },
      { id: 'chunk-19', name: 'Chunk 19', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZkQ/mTsBiiD-ajjq9QLoMNXZOWnoKe7h_miRi5nrYC_o7KQ` },
      { id: 'chunk-20', name: 'Chunk 20', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZlA/x9az32j7uTlRXZsg0Gr0i6VBQx6P30xqQNJx7OHYkpc` },
      { id: 'chunk-21', name: 'Chunk 21', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZmw/K3WK_ZJhMdrLWBfzd3k5QgLkCcrvc7eJZn9eHbwN1ys` },
      { id: 'chunk-22', name: 'Chunk 22', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZnA/WRFjkBlT8hyp5fVpZjhYTdIkvB1UAQ5tKrdui_cnEvI` },
      { id: 'chunk-23', name: 'Chunk 23', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZow/czjsexri1Ng2pmnbsTZB5lTMu_QpD3AyujkVr4teJV4` },
      { id: 'chunk-24', name: 'Chunk 24', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZqA/G3O-vj4kKvDMnKs6XEP3o7e5LzU-KRm1uh2a41UTAVo` },
      { id: 'chunk-25', name: 'Chunk 25', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZqw/3UjmVhkaCkkxaJxcVedK6TEU5BACjKJNjiCKxZrJFN4` },
      { id: 'chunk-26', name: 'Chunk 26', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZrg/qKEXmj2mE62U9R5H2CSBW9F-tk_UQk9RqUMJFRFX7Ao` },
      { id: 'chunk-27', name: 'Chunk 27', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZsg/ihcxdxUfdoxotU_TMiDhbbYzfGzC8jvROQ-PVcu6Zw4` },
      { id: 'chunk-28', name: 'Chunk 28', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZsw/5wTZaCdiJOGLVJ1ayCHqjxYaXkp-UoR-kbPuw1DAmLs` },
      { id: 'chunk-29', name: 'Chunk 29', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZtw/qbCjsY47ArWaft6T3HFLB6Y1mF9YDAvzg05bTcq2O7Y` },
      { id: 'chunk-30', name: 'Chunk 30', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZvQ/YhBC4KqGYOgexxSxD3ZikkSMpwe3n2BgKeW_QNnGgjw` },
      { id: 'chunk-31', name: 'Chunk 31', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZvw/RulVNlGn3-IshNg2IaBeVRfGodozujHia63hNUNduwg` },
      { id: 'chunk-32', name: 'Chunk 32', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZxQ/M1qWES9RH1pfFX_cOMFSjcUNXAM7QK7TwGFbx4Raofo` },
      { id: 'chunk-33', name: 'Chunk 33', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZyQ/A4WDdKAqUsNTlv_S0AUhDNx2kbKMu5_dl0UqcPvYQHE` },
      { id: 'chunk-34', name: 'Chunk 34', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZ0g/On0-6UGhYcJt_nyBUij9FznRUd6UjvhCSXdhKY0owzY` },
      { id: 'chunk-35', name: 'Chunk 35', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZ1g/ycUr4A9xtr61nmJ5ggA9FN5AGSaQljGx-vf7xL5NFP8` },
      { id: 'chunk-36', name: 'Chunk 36', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZ3w/f4-dkhhiPwtxgJ1zRx2fqT3nKGcsNCCjw4d59l9muts` },
      { id: 'chunk-37', name: 'Chunk 37', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZ4w/jurPJc7e0zxZ2AVZAY0zlsX7De668tdl5JBZD8ykYNw` },
      { id: 'chunk-38', name: 'Chunk 38', url: `${BASE_URL}/wt/AAAAAacs6bJKwHHJAACZ6A/LlF1owlp5GwbOl9EBgE0xGTIPqFHHbX-jmktFsBKnuo` },
      { id: 'chunk-39', name: 'Chunk 39', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACODA/bn74LQ2-MB3qIAnR_dQVMBbMhYqzYha6Eo7HEsE23fc` },
      { id: 'chunk-40', name: 'Chunk 40', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACODg/01uyo1b1_ztD5OLfnG-hJ4BPGWhFgmoXi2vIe3gxS3k` },
      { id: 'chunk-41', name: 'Chunk 41', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOEw/hY8sj0uvvZnWKLGhz6QE33UaciWvSTbD5wnizxlIMRE` },
      { id: 'chunk-42', name: 'Chunk 42 (Season 2 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOFQ/AyIMMqcfWVIv380T5IKLafMLZUoNIefgrIqLrLWPXXE` },
      { id: 'chunk-43', name: 'Chunk 43', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOFw/9V4FOUiYrRH3X4Vu65zxnOoT6PuIx6AccbEYfZZparI` },
      { id: 'chunk-44', name: 'Chunk 44', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOGg/Fngy3L1foBwUgKxSm5ogZTHIGUq9-eskMm9ymwOR-sg` },
      { id: 'chunk-45', name: 'Chunk 45', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOHA/ulO_vF_o5-vuGu8434lF9OJ1xXn6mcFMmLzmeI7Naig` },
      { id: 'chunk-46', name: 'Chunk 46', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOLg/fb107ETfE0wVNOIMOuNNxA2HAAfC8hrilvb5a0OAOdQ` },
      { id: 'chunk-47', name: 'Chunk 47', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOMg/TaKiYfYp8NaYOl-v8tQ3ny-kuBoeTkPgzLr8uLnC3hI` },
      { id: 'chunk-48', name: 'Chunk 48', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACONQ/lcQujifdIInj7b3kL4d-X2Otbc7vu7_MUvp1hVgsjuI` },
      { id: 'chunk-49', name: 'Chunk 49', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOOg/xm8NLNaGnWs4mH5aBupRi1UiizWWZql7emef2BsPlrc` },
      { id: 'chunk-50', name: 'Chunk 50', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOQg/P3iAl9B118vHt3Eh-Xu_HyPevG_a-okEnCv4Fxvxalo` },
      { id: 'chunk-51', name: 'Chunk 51', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOSg/YrIPa4UzWwJlAM0ZUb9_Ln6TEY7Vtd_KOpg5tvQjGkM` },
      { id: 'chunk-52', name: 'Chunk 52', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOTQ/vjFPyUnXuT1xrwuVKj9nNvfXZy30owxhJ02njXKCh38` },
      { id: 'chunk-53', name: 'Chunk 53', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOTg/Z1f4FlwhYxk7BZdbdBe6VRXlfSK2jhxyciykXhIc1Hw` },
      { id: 'chunk-54', name: 'Chunk 54', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOUg/W4QFoY9cz6XzmuHAOn-gSnY-aX1maQJc4Hq9X_VjrhM` },
      { id: 'chunk-55', name: 'Chunk 55', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOWQ/25FI0YAI_JcYl8EHNGA3GcFC50RRlBWQCHVoMXuSUIk` },
      { id: 'chunk-56', name: 'Chunk 56', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOYA/QsP8FhlVGZdx1k1YvREeJGR-brBckwLIAGYoagSjcKU` },
      { id: 'chunk-57', name: 'Chunk 57', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOZA/4CqC232REM9y83txHJG3rUdaDZ6vv4JNCO97bZUP9_g` },
      { id: 'chunk-58', name: 'Chunk 58', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOZw/4Xqy9nJ3xvrGR_YuZROjrjfxGEwStRJjdmRs05fHo0A` },
      { id: 'chunk-59', name: 'Chunk 59', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACObg/C92zcm9Pzg1hg3xZOMU3145qIF0s0za3Z_ionS0S3Ck` },
      { id: 'chunk-60', name: 'Chunk 60', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACOew/30PtsufvuIEUe3iAAWdsqYW4rPGcDALveboWW7ZOqOI` },
    ]
  },
  {
    id: 'the-beginning-after-the-end',
    name: 'TBATE',
    poster: 'the-beginning-after-the-end.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACN_w/gFIAPW1rXGLIVknEepOgEEE5qI8UCnRasuxrlQHSATI` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOAA/9heASU-4AQsx2CxfJ9-4PsRyN6ABVCRtR2Fi5LGAqBM` },
      { id: 'chunk-3', name: 'Chunk 3 (Season 1 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOAQ/RdbqQksMCOwwJCwz84E5k-aZ6TaaWcXXax-mwbcz4Ik` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOAg/4Xpw6kzWMsc1N1qNf9j0Fs2vryhLAtRXsoXqIMwC5Pg` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOAw/VYxs4rlfyf1QInk-RF5tTSljkcCBXn-TX3nd4if-E6Y` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOBQ/gZjje-ErEbHIhZ2Qpw0InLlPoEdQkCFHt4c7WyFqP6o` },
      { id: 'chunk-7', name: 'Chunk 7 (Season 2 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOBg/Yr6V4ICohg9KLfaK_VMa_z0g6iY-Cr1CdIA8rIKRhE4` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOBw/_jwNvbJl_coe-ocl9Laxvp4UviCj-wXeZxrTz-AJ1Ow` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOCQ/pAqySZvzDvuw6oKHT2HTzKjCuyqQcQyM_FeUC2_Mc7I` },
      { id: 'chunk-10', name: 'Chunk 10 (Season 3 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOCg/is_2fd44fyP1eNBRubmWNEXI1yr8V0OiPSzgQjMLNyQ` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACODg/EMuAA5lik9M-U_B-yEFqfWrC3-m8xN_fdGh3GCwyODA` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOEw/NycVs2cg420PinFbD9HBpWNUsDWmpYJe5I8ww2W5VFg` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOGg/awMfE61SpRHVf2WAmjb8O3Qe63U1vURdDKPrzRgBeZU` },
      { id: 'chunk-14', name: 'Chunk 14 (Season 4 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOHg/qSuxqnzJ2vrKxRGWnQ1O-N9y9hUq7SBNtEy5240JOWQ` },
      { id: 'chunk-15', name: 'Chunk 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOIQ/nPq9WM2ZpSaiUmUztprTyqB-cSU0_Bb3hgjXIm-hRx8` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOLA/w1W144LRFH-pIUgiQit7vy3EGD0eiG1idmbSTZM2k2U` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOMA/9ylc3OZtK5VXqkYjdty6SjRMat1nNL8oVs_ttlnEwQs` },
      { id: 'chunk-18', name: 'Chunk 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOMQ/rOv84aGQxx58rDnIWoKETQB_aQ6A9IzivrBjNXXyzqg` },
      { id: 'chunk-19', name: 'Chunk 19 (Season 5 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACOMw/m62Y8MKe0GmkdYTOo0YZ7xsP4Kijwu37sGGFvo-LVcY` },
      { id: 'chunk-20', name: 'Chunk 20 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJK0O07AACONQ/HTMCP1toYtdJN-VFX07RCZwo2-5VP4nNrZ7izGQV_Ss` },
    ]
  },
  {
    id: 'viral-hit',
    name: 'Viral Hit',
    poster: 'viral-hit.jpg',
    parts: [
      { id: 'chunk-1', name: 'Chunk 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNIw/hQ3-jhA1kxidBrhnskh7VcI8R7eUAcVsoMGycSRW6wU` },
      { id: 'chunk-2', name: 'Chunk 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNKg/l2VKvErYImdUAG0q1HF8sa81fBAnvMUDbcgw1N489-U` },
      { id: 'chunk-3', name: 'Chunk 3', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNLg/vtcBXjh2UI-g4kDZHfJlZHLzTXXO8TkqvlvNxG9vBcQ` },
      { id: 'chunk-4', name: 'Chunk 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNLw/t9o1t2otW7fQAIHi283MWP9YjphhvrXL5KvoPmgPC4M` },
      { id: 'chunk-5', name: 'Chunk 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNMA/iRktFL2MDuXvh5oJh2ZBloskIrVOcqYpRbTxd0AJ6Ug` },
      { id: 'chunk-6', name: 'Chunk 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNMg/RPtmn-w2l8KKPK18i2VePYQtiyZIwfE8uSdChb7lcoA` },
      { id: 'chunk-7', name: 'Chunk 7', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNNA/-MTa-7s8jsIXMhnp5pzsyaueAbfApbi_CS0XCs1FDHQ` },
      { id: 'chunk-8', name: 'Chunk 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNNw/urhYE3rz9QePBtXOS-sIFsIboJ55WbHM6OKkq_lTxi4` },
      { id: 'chunk-9', name: 'Chunk 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNOw/98Z0gPmT0hxrg_ea_gNwynu1Kz7TDJlF0tJRCroKFXM` },
      { id: 'chunk-10', name: 'Chunk 10', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNQg/cQ338KVnT22Fmy4L4lqis6QFsyr3pV8jWnVJpGqhUfE` },
      { id: 'chunk-11', name: 'Chunk 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNRQ/WfR9aiRIK0LCK9vJcG18llBL1thbvzGEkybujwkpPF8` },
      { id: 'chunk-12', name: 'Chunk 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNRg/k9nGRKXWVyxt6P2LoA_WiZJ_4MEibQahysoqLa1tlFU` },
      { id: 'chunk-13', name: 'Chunk 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNRw/_tPRz-u_9oOk4KY3_4hhjMG1uc4fczxW6qNuzBn58C4` },
      { id: 'chunk-14', name: 'Chunk 14 (Season 1 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNSg/3CKyZHsUvoE-Rb1MLVYWiHwKHQRut8ySM92a8MZws_c` },
      { id: 'chunk-15', name: 'Chunk 15 (Special)', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNSw/pzoqGmBu9Q4kR1bm1YnOrNQAFNUf04N76hsrJlJ1i_w` },
      { id: 'chunk-16', name: 'Chunk 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNTA/BZeHoW4L1b1WKHxpr9ehOIRFHnuwA43aArRKR47AhsU` },
      { id: 'chunk-17', name: 'Chunk 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNUA/BLdQQsz7Qgnsc_WdLXe3kfS-LhgGWdyxJUtIvuBZ02s` },
      { id: 'chunk-18', name: 'Chunk 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNUw/tG5mfdUMZata3-gCXKwevFb-VmWRDSSA_pBC6O3c8aI` },
      { id: 'chunk-19', name: 'Chunk 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNWA/V3OFg8Kb6vihiXCo-rfAJi7cst14bCEl1AerroEiJ_4` },
      { id: 'chunk-20', name: 'Chunk 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNWw/a3tBxjRdrp0gJ7KZEw4WMQ1c9pf-tl3faZLzIH3XCp0` },
      { id: 'chunk-21', name: 'Chunk 21', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNXQ/od6Usyw21_Swdl8L5qrnxgRWiLFW6PDegcEGX6Vhzkw` },
      { id: 'chunk-22', name: 'Chunk 22', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNXw/HKNZVwgzE3I9XjADcP5NomWpn-5cIEig7FASDuwXLW4` },
      { id: 'chunk-23', name: 'Chunk 23', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNYw/lo6UMRzwbs26bjqaEOqM19TjyvhFUrSO3tjWQFoIMto` },
      { id: 'chunk-24', name: 'Chunk 24 (Season 2 Finale)', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNaw/IzV3Ns43exZv4Rz7BRPZ3EnBrUlY6BSaieL-eJWXF30` },
    ]
  },
  {
    id: 'naruto',
    name: 'Naruto',
    poster: 'naruto.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPBw/pOp0kfBKMWWn-D9hogFdJLZuiC8kE3RXn7JHOD8KOP8` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPEQ/TpDXzETHjYs86JcYWOzvLleVbl3AlUAmIc3NsgNE2lg` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPEw/gI660OD-mKAswZKLpjkTeEFcSBJffTxevOo6pnBUpOA` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPFg/0K1Ooy5YITatuX5x-9qviLjeO9P-9NhocE9SM-NHSVE` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPGA/RoO3Mkxs4i8ewpdV4b2_PjtnHw5k3RM_3hVWTWLt040` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPHA/Q6AGsAUKt0SUNbadeOwCKg-SSoNP-STpYYjHioWucwk` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPHQ/WZ63v3nS518q3InOyNzyw7euEChb0r5z4SEoklgG6ps` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPHg/iU9P2wvb9iDQy42F0nkQmQSQx1o-nwOTBg2BtzERV6o` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPHw/wUnX_yMQVrsktlinal2wxKAr0RJhcM-fxGkPhBRhepE` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJKwO07AACPIg/S-OFAmqJdV0h6QDOSFzk__st6pnlUtiz5_29E49_U8U` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRKA/Otf30ytknqo2BOaTsvHR8K2ZgWhTEsWb5uTO6CvjJc4` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRKg/oj6L27leLJpy7Llm4ts7G7OXKyE-cgpg7cnkvr0z5Bs` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRLA/y61ds-r1uzasM4TC2-tVvFXd5LYtdDCUjxqUm1M7FuI` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRLw/lYfkxR8_TCKDKomjgQqMD4FklykoIyM0uxPIyEasmGs` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRMg/xgXw_12Z188mtYkAeGlBaJsWH0C9s9fEgb0fxyFQuV4` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRNg/dfgza0UUDctTmdb9SvCN9EzLPqY6kctFuIvLCpftIAw` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRNw/YKi1iPQ37g7EZs3kB6IXLUA8yi2SVWtD-wsFgVvqzsA` },
      { id: 'volume-18', name: 'Volume 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACROQ/GCOlANoQC0e5mxtXoHONqsH7iHDlVmHySExJJQ9nIao` },
      { id: 'volume-19', name: 'Volume 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACROg/5nbfKlcMAy5k2boUiB92koV_CNwSsBReFdJjIq3Uxn8` },
      { id: 'volume-20', name: 'Volume 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACRPQ/6v7wiB7CEyWerUC00WF5aW6aH8tbiHWHge5XiXRnqzg` },
    ]
  },
  {
    id: 'boruto',
    name: 'Boruto',
    poster: 'boruto.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMBg/8tEDxGCfNkVODiRiPkYQrm-gF9IagP37q-dAeDr1laY` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMCA/NEmT1yO4D0A35Mpdyg-E_4qIYkIjvuL-IDWsBz7rBeQ` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMCQ/1lmZrGpTw76grfrJsvd5m4cT3tU0lHfs87A01hms2qI` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMCw/nhM7hH72Wqg9JyQpMk-tVbzzFas725t6Vph6-DFyl2k` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMDQ/ok-ZmGTN0ORZXvHbaUL3JVerKu8HH_LpZvG82hVOzb8` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMDg/6dncPuZejJ7NmSrvp6NGxGBiE4RdomMr77AiCAicJpU` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMEA/-KJ2xT_7xtkM9OglJ3RGDTDNyPloLH8_VwVqnBYTf_A` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMEg/5S7CJCtKDtGjlw5TkE1ZLsMePlmgn7opympJ53ixtQQ` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMEw/Ht1gioxlh-tZKdqG-ykVi1s5oWExXSsZh_aBJH1fIkA` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMFA/52xVzAKz3EbeD6MyGXP9uzfFlymZkzyjpfH17SsIIBY` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMFQ/c1MefVkmyoAlhQ3Z67nfplsFIBs0AheLEr6dZUiy5rk` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMFg/d1QjWcprhcKdwAP6UF56KI2bKFJ3RQDIodBuCQTkYyk` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMGA/UBSsY9OeHCd82J7XnSmRojxgAUA5p08iwYcFXdA97RE` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMGQ/bIlrVWqQiftMod2CajZwZHmUpCF_smbULhmrPlbxdqw` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMGw/tpjK26exLB6qW36Ekoduv9HBttKd3EeO1-rmvPzwn6E` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMIA/ZpXr1XFPumuDTJ-QKo7Ldh8WwN5Lb_qXu2RkZtaFoFM` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMIQ/u4LFMqPhG4yzI6bUSI-tItt5tr2t42u7Pkk-CTjgRUk` },
      { id: 'volume-18', name: 'Volume 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMIg/w_5Cm9nvjX45Xr9VzDH_O_vqtu4DVVexAG04KfpATs0` },
      { id: 'volume-19', name: 'Volume 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMIw/MIgSEzewujAWMwz2wH7dNKoAKTFHFEcHSOZWDg-Xkh4` },
      { id: 'volume-20', name: 'Volume 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMJA/GY9f1YslZJC-ThXfdVEyEqm7e8G1DbmhKfk0FU3fVV0` },
    ]
  },
  {
    id: 'jujutsu-kaisen',
    name: 'Jujutsu Kaisen',
    poster: 'jujutsu-kaisen.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-0', name: 'Volume 0', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXvg/ma5_Cs3aks8Iu_nBOScqhceQFdMyfsTSC1B9hrLiOng` },
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXvw/VFkDw86aIlCiQOY24ogn6yegJVvXM64qXqOs9Ux6FL4` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXwQ/c3_GRb3dPMOI0g7wwH98uc82PLnYm113Xl3KqK85yNE` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXww/0hdTOJyotg26eNiuBxEWOSFtNwZZLp4UbkAFqWR_dos` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXxQ/K6lKEVVUQZCJswnKWk6HRmf_aWO3_2ehrbrMUW7YvKQ` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXxg/elYZ7e0TbayyTEnVsrDoT_BTBwHQtPUaVUkpzH6pxmI` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXyg/Tg-PQyKrU6T2GLxETLWE7dG1-GYCkYCvQQiZ5K8tLac` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXyw/IzTbHY6xulz-bAUywRxh9MksagqGhHpqvOvbh7is1bg` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACXzg/hEb3V0U0TWZMRyvraWc3zQZp5V-k1ELUQvSXEAUMbGE` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX0A/HrH5hVlsCYZrFaAwElNOKHcvluDopDPWNVKiRS2XnNU` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX0g/WRDcWyRnciK5v56mEY5VMyzTDzI_0cPciXZK3Y3fLGE` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX1g/E1K_sYr0f4g7vbHCz08jTic6aiGMhS4D4zfKLL1VwgM` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX2g/s4es6R7u0KMmL60oHqjq8_cWF0VJbq9W0sKJueiHMp0` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX3A/Z9je47OU5NWsKmSXq9-1yFcSR5MtZ4vqNgsRhELdpxw` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX3g/d29sI5iGI7N2r_sxsKffLGOC2F9H05DxazpsAUuNmcY` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX4A/zruuItJ_wjTc2TU1A9voBgmDnTnc34Mhe6zPNEHb6iA` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX4g/heuBIzgAInAmU9LezMcCkpcgNT2tpOt2k8tPx-0BNjE` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX5A/YaGRtauwSrMXyf70FZUmOmam2zoAPAuBYm8fIS_slCc` },
      { id: 'volume-18', name: 'Volume 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX5Q/aRpl05RCyk0CvHTTyG3FZhyuTVV8sJDfO2ZslkDFv9g` },
      { id: 'volume-19', name: 'Volume 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX5g/Zfixar4hM_OkNoH6jqIkBQ27Yc_r_CxCmQ27iwk0QBQ` },
      { id: 'volume-20', name: 'Volume 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX6Q/Vn7pilj3DEtMDSEpzD6vm7XkQejuPVpfzRFzQaevT9A` },
      { id: 'volume-21', name: 'Volume 21', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX7A/CfHijQb1GIg_j639nWphHFcYTctr4lPZ78lo4xhE9gA` },
      { id: 'volume-22', name: 'Volume 22', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX7w/4ua46Hxcd_xsaUSmjLV-zqcOkLFxkMP-UWcfnwHDR7A` },
      { id: 'volume-23', name: 'Volume 23', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX8Q/Hh5ui4HUPfRPC6fYUWFWsXkcm-oacrnDeB3hLKntnUc` },
      { id: 'volume-24', name: 'Volume 24', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX8w/Y0SBSf0QEbe6x0izYTpKonq3CekW5DNUGKVhbWj-6rA` },
      { id: 'volume-25', name: 'Volume 25', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX9A/gCocWYAAFmOMkLhk4tP3mgwuD_gr8dw4UYbRLI3XQsQ` },
      { id: 'volume-26', name: 'Volume 26', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX9Q/0iNV0gq-OXhKpjNIZspSwML1kC8jUIzATID9nelMrs0` },
      { id: 'volume-27', name: 'Volume 27', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX-A/FtFg8SH_sv6RxmtifcezIQG66d7QvmLHRiBX4Q2DV0U` },
      { id: 'volume-28', name: 'Volume 28', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX-g/yZRlrkcTYi61wXRV2kQaWF0UYSvz0ctBGDUHdoj7Dys` },
      { id: 'volume-29', name: 'Volume 29', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX_A/8ZaRofOcuk_qRgCTE7WGGoxrR-UKGV4hUVJx_iw7ofA` },
      { id: 'volume-30', name: 'Volume 30', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX_Q/ElEOvorJX8Xh6Udj2PH_NhbbeuY1uMIfFnjpq9kBj9E` },
      { id: 'volume-31', name: 'Volume 31', url: `${BASE_URL}/wt/AAAAAacs6bJK0OhrAACX_g/lmEeyd_ShBHnBKRo7pvxnZXeFR0-MMvo-6GwfNaglCc` },
    ]
  },
  {
    id: 'chainsaw-man',
    name: 'Chainsaw Man',
    poster: 'chainsaw-man.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNeA/YCqV2K_beOk3TU_u1lJNPgGPSYHIBLBJeU_sx3Q1Jbs` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNfQ/08Vbppigs7KfI4BqZkjvta_bqK8L_2B-dnvyqaMbopU` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNgQ/zZ_1meF9aeEBTP_gZjRYeFTEsUEQYun1nLQ6iMFHq1U` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNjA/f1g6_0WKvf5N5eqlLL4K8TuOpDgxIwTLwptbGjPMRJ4` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNjw/blkcDNV4ZYvC6YMHIFcsQAgajDvkbOBM3TjpATV1ZkI` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNlg/2SfKkcyK4XK2BeffIVivVHZWAc0XM8Vkht4HJ0c2OFQ` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNmw/TxHi07WUWHFKTA7S6BsGKBUWMo_Z4euQQ0xja4eveCM` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNpA/OZvBXGPtB6EVLAEuxdlMjLD_1qDoEEgNMOgUMx7ixfI` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNrQ/eT2dCdzb7FNp6W48U5cq1eO6z86qhzvAzRquaLzLWd4` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNtQ/hTIHcFuiAHMxMN4VkLEVVtWmx2DWjtlI45DOfBnxvU8` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNuw/wHuQP_zOlS6tlTwgzVfGefaVzg0k77zo-DQWbuNgeUY` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNvw/omZ6gSroKT4h3tz3ympQ8mtPVeDvWAtQ98TLewNO0_Q` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNww/5VHM8zUM1hLwDwtBODTMPPsn0_jZHuWI9iRoKrZaBZs` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNxA/_N0Y7vxLQ8tAnYjF02sWlZApqZK-3uW8BT5MgkuU4Z0` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACNyQ/W3x1pcwRkpTKEzioj4T5fOnT7-fuwUvvQ63vzYazh60` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACN0g/xCEbMKnBoYf7gwKP7N8uVY03B6DGF16nQqRw2n1azvo` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACN3w/xqT_5U7pOlabTyzdlhtMqMndQRSmg6165M6rfbnVckk` },
      { id: 'volume-18', name: 'Volume 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACN5Q/wTP8vanJXKa173rRzEvHSutOoxNMX3PpeeuxXxDJRWY` },
      { id: 'volume-19', name: 'Volume 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACN6A/XRg0cIHTaT5PEqNYkjDHzso5FShtx37oi8VRT41AME0` },
      { id: 'volume-20', name: 'Volume 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACN6w/M2m89hBAUKL8nSa5yvWNmOXEpjuy7brsiIA4Fmn7-Nc` },
    ]
  },
  {
    id: 'dandadan',
    name: 'Dandadan',
    poster: 'dandadan.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh8w/pcBNYbpu70EQXKBQIvmbq2PHJiNpirczwAZ-YWnA6Ks` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh9Q/K8bkX6apgPxAYj-edgxsQqldjcd0HdJBVy-dFEFzQXw` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh-A/MMUBv4wTsD5osDevd6RNNxmOMWp-vH2ih_BWt7O9wlU` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh-Q/DHbygeoySoHioxHYAbn5Q6IR1F5CPuoWALsNN95doZs` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJKqXlHAACh-g/y9Cerpau9_HgNApJS97m2bD4mUd47DdbieXgCjDGR_s` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACThQ/79wQasdmSMySEd023KqjACxXQwcaFXKW5NEBpIj12Lc` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACTnQ/3FmhyVtHDtkZaFRv7OtL6o4WPOnk-TolR8YuDZx3fcI` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACTxQ/XKIq9iIl0bQ8hb0DLMlXeKqq-BZVx3i9KBoZDYSCtmY` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACTzQ/CosLM7Ow-SeAMwaL86EvdCbHkdScS9m-4Vug4nFAcAU` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACTzw/CFRc1Yif5fy4b3i7GMdZYiBEa5U9wzmJ6zEpJJU2Hss` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT0A/lMM5d0DADhQXl4vVAq4lzCJmhke9aPzjCmzORpoQjE4` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT0g/l0BKwPezqhJr3gtGqrqzyU6nE-HgdotHK2aGDu1cQrg` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT0w/8EVsNaxzhiXCUx69az_GKzKKjSrEICw6Zx7f-UiILw8` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT1A/VMn5lOCOnid1O2ZFvsyo9sm8VNu12Rwzs_ZWZ67Eq0Y` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT1Q/YhFVo7byEBZaHH6YR8p6AX89hmORapLuv3FXJih1JaY` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT1g/sUExUwxJxiEpB-yVz2qG9WNX6lI3nzh3_NzFf0e08l4` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJKsXlHAACT1w/9_vj9Yg-moIA2Ssv_9M9l3_iuJfjRhAUyUwBI9QVUtY` },
    ]
  },
  {
    id: 'blue-lock',
    name: 'Blue Lock',
    poster: 'blue-lock.jpg',
    gap: `${GAP}`,
    parts: [
      { id: 'volume-1', name: 'Volume 1', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMPw/Yl946TzBFoPi1MWFlp4myLaVrV0DRGaBGbxUwB1FSX4` },
      { id: 'volume-2', name: 'Volume 2', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMRg/ZGAKnypjyGK9G9ludb7jZ5szNLBzQ0nKbCihvAO3DaE` },
      { id: 'volume-3', name: 'Volume 3', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMSA/00s0Eiz6OUkRDYVPRp97elhD1tZkgQIXvEd_w6vBsEI` },
      { id: 'volume-4', name: 'Volume 4', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMSg/MJQwGNi1BiZK_3jWLR19Sj02S2lkSI6lPSbyrYzm2O0` },
      { id: 'volume-5', name: 'Volume 5', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMTg/IHln0WCxjtcvYt8DZzpwl5sp37HCFVvcA2qD2gB531U` },
      { id: 'volume-6', name: 'Volume 6', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMUQ/vdTOOITTDxy7fdkNfP4BDrlEq6ncnigvBnc59MW5PTs` },
      { id: 'volume-7', name: 'Volume 7', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMVA/W83dvWxz9aUIttKxdv8DrAZgYfJCDq_Uv6hHg5zZ5mE` },
      { id: 'volume-8', name: 'Volume 8', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMVQ/jApNHI2eg0d85h4BRMOd9InnugBS-O_4Oaggivs5oDM` },
      { id: 'volume-9', name: 'Volume 9', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMWA/FjUjyr8KzlpvfgkB4XFDcElhgy-qq6o7E3F_cgaGujA` },
      { id: 'volume-10', name: 'Volume 10', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMXA/niwjIs1lSMAxVq6rv86nxmjrIi1vU56oDEzWxubgE7U` },
      { id: 'volume-11', name: 'Volume 11', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMXQ/zLYtcBVENqWgLku4wE8kkdXISVeYKtwJkWxEWUIiKyk` },
      { id: 'volume-12', name: 'Volume 12', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMXw/Fxr07Ro_LYJ90OMI5uLfL8g-gKmYdA_TH1jhja-4IuI` },
      { id: 'volume-13', name: 'Volume 13', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMYQ/uVdp04OUX2RtLU532SzMvttj-mff4oMBg3NydnzWDDA` },
      { id: 'volume-14', name: 'Volume 14', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMZg/AFV8AC1PSOkcCA2rNXHo0aLjDC1FH-JBXMVVB-77Wqw` },
      { id: 'volume-15', name: 'Volume 15', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMbg/rdWUqeLxLI3MAgQPM8BxUiZrVbZ8wpT844TSVknvQ34` },
      { id: 'volume-16', name: 'Volume 16', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMdA/0hYOp3f04MbiBpOKwENcRpJ3UVHDx2zo3JE9pg3IPW4` },
      { id: 'volume-17', name: 'Volume 17', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMeQ/-arOyx6txGDMs7TqBUIefELHgoaKtbFE6fqGnVYqzz4` },
      { id: 'volume-18', name: 'Volume 18', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMew/of3x_frQptrYCxfxGQ3Rhuh8bUQlQptb8BL6IKdVPmg` },
      { id: 'volume-19', name: 'Volume 19', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMgA/rYnFthzZ4I25srfLgBwjJ-AOXLn0j4eq2ld0DXHilgI` },
      { id: 'volume-20', name: 'Volume 20', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMhQ/AQV_CkXf2OSsTRiJE60uJzow0fcg6O1FkkFtJ4R9nEI` },
      { id: 'volume-21', name: 'Volume 21', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMhg/q1u5lVkJnc8PK6RtuJ4fVw1skADpq3VvsIT0laoyidc` },
      { id: 'volume-22', name: 'Volume 22', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMkg/vRPaX8fXiF1ZCGQ12hO6riBOpdsyfcDy4899JphaH8g` },
      { id: 'volume-23', name: 'Volume 23', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMlw/sm9yf_E20XiPplX_IOWUU9uD5e8ajAq54vAsMdCdSzs` },
      { id: 'volume-24', name: 'Volume 24', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMmw/nhHxZu6WuTyPxnBABLusDGH90GsQxcsHE5YIeYMxGRE` },
      { id: 'volume-25', name: 'Volume 25', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMog/W1y7qlfrFREbQX9skZAaHm2lAFG6v-U5Kv7nLWRK87Y` },
      { id: 'volume-26', name: 'Volume 26', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMrQ/gViv6HnTjNK3UmD3DTqyLd9Iqcb-CjY6Dig5I-B-HDk` },
      { id: 'volume-27', name: 'Volume 27', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMsQ/u8Z_Km5-wIdq0zHXTpvZlZBnFEfVzEMDs5etfjJ7MIw` },
      { id: 'volume-28', name: 'Volume 28', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMsw/2AFBHDXGbl3yfuJ6nHDZP7uvfXWiwajjNbhpTaYTm5M` },
      { id: 'volume-29', name: 'Volume 29', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMuA/F4yWDNGTSI-qdUsEfRO32uf2V9mL3pPASkG31L4DqZQ` },
      { id: 'volume-30', name: 'Volume 30', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMuw/NrNygNUn3zmHwjSZn-SQ3b1ByahOrK-Q8p4lMV-tEA0` },
      { id: 'volume-31', name: 'Volume 31', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMwA/0NYrag4kRw_vCXKFb-QW8rDS-xHBFs5RI1qb79tCYH0` },
      { id: 'volume-32', name: 'Volume 32', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMxA/D5BDedPJSF9FDPOmDCCHtTmSpeA_64cF7LkiT4oJHRQ` },
      { id: 'volume-33', name: 'Volume 33', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMxg/qPlqoMyFDpSoRijVRi7YIhrLyMM_p20BGxQsFgdbQTo` },
      { id: 'volume-34', name: 'Volume 34', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMyQ/oTEBLi1lI9U13VqjvWeLoHAgtDWc68dVwk2EOxilwgA` },
      { id: 'volume-35', name: 'Volume 35', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACMzw/VRqHZHA4bnk8lhxVa-0443dwoJRVtHxHdBJva_jMJIc` },
      { id: 'volume-36', name: 'Volume 36', url: `${BASE_URL}/wt/AAAAAacs6bJK0QUJAACM0A/HqQn5g1Aa9vUAEyWzhwrmR8oMDrPqkGvI5HRlFruMAo` },
    ]
  },
]
